version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:8081"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=8081
    # Alternative for environment ==>
    # env_file:
    #   - ./.env
